import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/general/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./_trpc/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calendai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <Provider>
      <body className={`${inter.className} antialiased`}>
        <Navbar />
        <div className="h-screen w-full grow p-6 md:overflow-y-auto md:p-8">
          {children}
        </div>
      </body>
      </Provider>
    </html>
    </ClerkProvider>
  );
}
